sudo: required
dist: trusty

branches:
  only:
    - master
    - develop

services:
  - docker

install:
  - curl -SsL https://github.com/tsenart/vegeta/releases/download/v6.3.0/vegeta-v6.3.0-linux-amd64.tar.gz | sudo tar xzf - -C /usr/local/bin

before_script:
  - export FIXUID=$(id -u); export FIXGID=$(id -g); ./ci/docker-up.sh

script:
  - ./ci/test/unit.sh
  - ./ci/test/functional.sh
  - ./ci/test/stress.sh

notifications:
  email: false
